<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <RootNamespace>UnlockFps</RootNamespace>
    <AssemblyName>unlockfps</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
    <MinVerTagPrefix>v</MinVerTagPrefix>

    <Authors>Milkitic</Authors>
    <Product>Genshin FPS Unlocker</Product>
    <Description>Genshin FPS Unlocker</Description>
    <Copyright>Copyright © Milkitic $([System.DateTime]::Now.Year)</Copyright>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
    <PublishTrimmed>true</PublishTrimmed>
    <PublishAot>true</PublishAot>
    <TrimMode>link</TrimMode>
    <OptimizationPreference>Size</OptimizationPreference>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>

    <DebuggerSupport>false</DebuggerSupport>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
    <EventSourceSupport>false</EventSourceSupport>
    <Http3Support>false</Http3Support>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
     <InvariantGlobalization>true</InvariantGlobalization> 
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <MetricsSupport>false</MetricsSupport>
    <StackTraceSupport>false</StackTraceSupport>
    <UseSizeOptimizedLinq>true</UseSizeOptimizedLinq>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.13" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="FluentAvaloniaUI" Version="2.5.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.49-beta">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Milki.Extensions.Threading" Version="0.0.36" />
    <PackageReference Include="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!--<PackageReference Include="PublishAotCompressed" Version="1.0.3" >
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>-->
    <PackageReference Include="Semver" Version="3.0.0" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\unlockfps\unlockfps.csproj" /> -->
  </ItemGroup>
</Project>
